import React, { useState } from 'react';
import { Download, CheckCircle2, FileText, RefreshCw } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { Sidebar } from './Sidebar';
import { t } from '../utils/translations';

interface DossierStageViewProps {
  researchData: any;
  language?: string;
}

export const DossierStageView: React.FC<DossierStageViewProps> = ({ researchData, language = 'en' }) => {
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  const productName = researchData?.productName || 'Herbal Immunity Formulation';
  const ingredients = researchData?.ingredients || 'Curcuma longa (Haridra) + Azadirachta indica (Nimba)';
  const productStage = researchData?.productStage || 'Pre-Clinical';
  const jurisdiction = researchData?.jurisdiction || 'India';
  const auditId = `AYU-${Math.floor(100000 + Math.random() * 900000)}`;

  const nextActions = [
    "1. Review prior-art finding under Section 3(e) Combination Index",
    "2. Verify required stability and heavy-metal testing evidence for SLA AYUSH Form 25D",
    "3. Check applicable regulatory pathway for export expansion to US FDA DSHEA"
  ];

  const exportPDF = () => {
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(5, 150, 105);
    doc.text("AYUDISHA — VERIFIED RESEARCH DOSSIER", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Audit Trail ID: ${auditId} | Jurisdiction: ${jurisdiction} | Date: ${new Date().toLocaleDateString()}`, 14, 28);
    doc.line(14, 32, 196, 32);

    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(`1. PRODUCT SUMMARY`, 14, 42);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(`Product Name: ${productName}`, 14, 50);
    doc.text(`Ingredients: ${ingredients}`, 14, 56);
    doc.text(`Classification: Proprietary Ayurvedic Medicine (Rule 161)`, 14, 62);

    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(`2. IPR & TRADITIONAL KNOWLEDGE FINDINGS`, 14, 74);
    doc.setFontSize(10);
    doc.text(`- TKDL Reference: Retrived Charaka Samhita polyherbal reference formulation.`, 14, 82);
    doc.text(`- Prior Art: WO/2021/08912 overlap. Requires Sec 3(e) synergy CI proof.`, 14, 88);

    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(`3. REGULATORY PATHWAY`, 14, 100);
    doc.setFontSize(10);
    doc.text(`- Framework: Drugs & Cosmetics Act 1940 (Rule 161 / Schedule T)`, 14, 108);
    doc.text(`- Licensing Authority: State Licensing Authority (AYUSH) Form 25D`, 14, 114);

    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(`4. RECOMMENDED NEXT ACTIONS`, 14, 126);
    nextActions.forEach((act, idx) => {
      doc.setFontSize(10);
      doc.text(act, 14, 134 + (idx * 6));
    });

    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("AYUDISHA provides source-grounded research guidance based on retrieved statutory laws. Not legal advice.", 14, 280);

    doc.save(`${productName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_dossier.pdf`);
    setDownloadSuccess("PDF Dossier exported successfully!");
    setTimeout(() => setDownloadSuccess(null), 4000);
  };

  const exportMarkdown = () => {
    const content = `# RESEARCH DOSSIER — AYUDISHA\n` +
      `**Audit ID:** ${auditId}\n` +
      `**Date:** ${new Date().toLocaleDateString()}\n` +
      `**Product:** ${productName}\n` +
      `**Ingredients:** ${ingredients}\n\n` +
      `## PRODUCT CLASSIFICATION\n` +
      `- Proprietary Ayurvedic Medicine under Rule 161\n\n` +
      `## IPR & TRADITIONAL KNOWLEDGE\n` +
      `- TKDL 3 classical references retrieved\n` +
      `- Prior art overlap identified (WO/2021/08912)\n\n` +
      `## REGULATORY PATHWAY\n` +
      `- SLA AYUSH Form 25D Licensing Pathway\n\n` +
      `## NEXT ACTIONS\n` +
      nextActions.map(a => `- ${a}`).join('\n') + `\n\n` +
      `*Generated by AYUDISHA — Where Ayurveda Meets IPR & Regulation*`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${productName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_dossier.md`;
    a.click();
    setDownloadSuccess("Markdown file exported!");
    setTimeout(() => setDownloadSuccess(null), 4000);
  };

  const exportJSON = () => {
    const jsonObj = {
      auditId,
      timestamp: new Date().toISOString(),
      productName,
      ingredients,
      productStage,
      jurisdiction,
      classification: "Proprietary Ayurvedic Medicine",
      tkdlReferences: 3,
      priorArtMatches: 2,
      regulatoryAuthority: "State Licensing Authority (AYUSH)",
      nextActions
    };

    const blob = new Blob([JSON.stringify(jsonObj, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${productName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_dossier.json`;
    a.click();
    setDownloadSuccess("JSON Dossier exported!");
    setTimeout(() => setDownloadSuccess(null), 4000);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-6">
      <div className="flex flex-col lg:flex-row gap-8">
        {/* Left Workspace Sidebar */}
        <Sidebar
          activeTab="dossier"
          setActiveTab={() => {}}
          language={language}
          researchData={researchData}
        />

        {/* Main Content Area */}
        <main className="flex-1 space-y-6">
          {/* Header Title & Subtitle */}
          <div className="border-b border-slate-800 pb-4 space-y-1">
            <h1 className="text-2xl font-extrabold text-slate-100 uppercase tracking-tight flex items-center space-x-2">
              <span>{t('dossierTitle', language)}</span>
              <span className="text-xs font-normal normal-case px-2.5 py-0.5 rounded-full bg-emerald-950 text-emerald-300 border border-emerald-500/30">
                Stage 6 of 6
              </span>
            </h1>
            <p className="text-xs text-slate-400">
              {t('stage6Sub', language)}
            </p>
          </div>

          {downloadSuccess && (
            <div className="bg-emerald-950/80 border border-emerald-500/50 text-emerald-300 text-xs p-3.5 rounded-xl font-medium flex items-center space-x-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>{downloadSuccess}</span>
            </div>
          )}

          {/* MAIN DOSSIER DASHBOARD CARD */}
          <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 md:p-8 space-y-6 shadow-2xl">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-4">
              <div>
                <h2 className="text-lg font-bold text-slate-100">{t('researchDossierHeader', language)}</h2>
                <p className="text-xs text-emerald-400 font-medium">AYUDISHA Source-Grounded Research Summary</p>
              </div>
              <span className="text-xs font-mono text-slate-400 bg-slate-950 px-3 py-1 rounded-lg border border-slate-800">
                {t('auditTrailId', language)}: <strong>{auditId}</strong>
              </span>
            </div>

            {/* PRODUCT */}
            <div className="space-y-2 border-b border-slate-800/80 pb-4">
              <span className="text-[10px] uppercase font-bold text-slate-500 block">{t('product', language)}</span>
              <h3 className="text-sm font-bold text-slate-200">{productName}</h3>
              <p className="text-xs text-slate-400">
                Classified as <strong>Proprietary Ayurvedic Medicine</strong> under Rule 161 of Drugs & Cosmetics Rules 1945.
              </p>
            </div>

            {/* IPR & TRADITIONAL KNOWLEDGE */}
            <div className="space-y-2 border-b border-slate-800/80 pb-4">
              <span className="text-[10px] uppercase font-bold text-slate-500 block">IPR & TRADITIONAL KNOWLEDGE</span>
              <div className="text-xs text-slate-300 space-y-1">
                <p>• <strong>TKDL Findings:</strong> 3 classical references retrieved in Charaka Samhita oral formulations.</p>
                <p>• <strong>Prior Art Overlap:</strong> WO/2021/08912 matched; Section 3(e) Chou-Talalay synergy proof required.</p>
              </div>
            </div>

            {/* REGULATORY PATHWAY */}
            <div className="space-y-2 border-b border-slate-800/80 pb-4">
              <span className="text-[10px] uppercase font-bold text-slate-500 block">REGULATORY PATHWAY</span>
              <p className="text-xs text-slate-300">
                Current Pathway: <strong>State Licensing Authority (AYUSH) Form 25D Application</strong> + Rule 161 Packaging.
              </p>
            </div>

            {/* EVIDENCE STATUS */}
            <div className="space-y-2 border-b border-slate-800/80 pb-4">
              <span className="text-[10px] uppercase font-bold text-slate-500 block">EVIDENCE STATUS</span>
              <div className="flex items-center space-x-4 text-xs font-semibold">
                <span className="text-emerald-400 font-medium">✓ 5 Supported</span>
                <span className="text-amber-400 font-medium">⚠ 1 Needs Review</span>
                <span className="text-slate-500 font-medium">? 1 Missing</span>
              </div>
            </div>

            {/* NEXT ACTIONS */}
            <div className="space-y-3 border-b border-slate-800/80 pb-4">
              <span className="text-[10px] uppercase font-bold text-slate-500 block">NEXT ACTIONS</span>
              <div className="space-y-2">
                {nextActions.map((act, idx) => (
                  <div key={idx} className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-200 font-medium">
                    {act}
                  </div>
                ))}
              </div>
            </div>

            {/* EXPORT ACTIONS */}
            <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
              <div className="flex flex-wrap items-center gap-2">
                <button
                  onClick={exportPDF}
                  className="bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs px-4 py-2.5 rounded-xl transition flex items-center space-x-1.5 cursor-pointer shadow-lg"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>{t('downloadPDF', language)}</span>
                </button>

                <button
                  onClick={exportMarkdown}
                  className="bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800 font-semibold text-xs px-4 py-2.5 rounded-xl transition flex items-center space-x-1.5 cursor-pointer"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>{t('exportMarkdown', language)}</span>
                </button>

                <button
                  onClick={exportJSON}
                  className="bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800 font-semibold text-xs px-4 py-2.5 rounded-xl transition flex items-center space-x-1.5 cursor-pointer"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>{t('exportJSON', language)}</span>
                </button>
              </div>

              <button
                onClick={() => window.location.reload()}
                className="text-xs text-slate-400 hover:text-white font-medium flex items-center space-x-1 cursor-pointer"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>{t('startNewResearch', language)}</span>
              </button>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};
